"""
QuantOS™ v11.0.0 - Secure Setup Wizard
Copyright (c) 2026 Cemini23 / Claudio Barone Jr.
"""
import os

def run_setup_wizard():
    print("\n🔒 QuantOS Midnight Edition - Secure Setup Wizard")
    print("This will generate your local .env file. These keys will NEVER be uploaded to GitHub.\n")

    # Expanded keys to match existing project requirements
    keys = {
        "ACTIVE_BROKER": "Primary Broker (alpaca, robinhood, ibkr, etc.)",
        "ALPACA_API_KEY": "Alpaca API Key ID",
        "ALPACA_SECRET_KEY": "Alpaca Secret Key",
        "RH_USERNAME": "Robinhood Email",
        "RH_PASSWORD": "Robinhood Password",
        "BQ_PROJECT_ID": "Google Cloud Project ID (e.g., gemini-financial-suite)",
        "BQ_DATASET_ID": "BigQuery Dataset ID (e.g., quantos_live)",
        "BQ_TABLE_ID": "BigQuery Table ID (e.g., market_ticks)",
        "GOOGLE_APPLICATION_CREDENTIALS": "Full path to your Google Cloud JSON key",
        "TV_WEBHOOK_KEY": "Secret phrase for TradingView Webhooks",
        "DISCORD_WEBHOOK_URL": "Discord Webhook URL for alerts"
    }

    env_content = "# Generated by QuantOS Setup Wizard\n"
    for var, prompt in keys.items():
        value = input(f"Enter {prompt} (or press Enter to skip): ")
        if value.strip():
            env_content += f"{var}={value.strip()}\n"

    # Write to the root .env relative to this script
    with open(".env", "w") as f:
        f.write(env_content)
        
    print("\n✅ Setup Complete! Your .env file has been generated securely.")
    print("⚠️  CRITICAL: Ensure '.env' is listed in your .gitignore file before pushing!")

if __name__ == "__main__":
    run_setup_wizard()
